### ISSUE TITLE
Error loading panel

### ISSUE THREAD

**Issue by bhozar** [simPod/grafana-sankey-panel#1]
Thought I would give your code a go to see if it's a working graph but I unfortunately get an error `
Error loading: simpod-sankey-diagram-panel`

```
Error loading panel plugin: simpod-sankey-diagram-panel SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at st (system.js:4)
    at system.js:4
    at system.js:4
    at O (system.js:4)
    at k (system.js:4)
    at system.js:4
(anonymous) @ keybindingSrv.ts:21
```

I installed by cloning the .git to the plugin directory on Grafana 6.5.0-beta1.

**Comment by simPod** [comment]
@bhozar did you also build it? I don't commit `dist` folder.

However, the plugin is very specific for my use case for now. I have to use it with json datasource so my backend can provide proper data shape.

**Comment by bhozar** [comment]
Fair enough. Thought I would give it a go. I get an error when I ran npm i against it. Not at my PC at the moment to grab the message. As I'm not using it with the JSON backend like you I expect it will not work for me as my intended use is ElasticSearch.

**Comment by simPod** [comment]
You'd have to find a way to provide it with data in shape as documented here https://github.com/simPod/grafana-sankey-panel/blob/52fe6ea/src/sankey.tsx#L13-L31

It doesn't calculate sankey relationships on client side.
